dresscollector/urls.py
from django.contrib import admin
# Don't forget to import the include function:
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path 
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('dresses/', views.dresses_index, name='index'),
    path('dresses/<int:dress_id>/', views.dresses_detail, name='detail'),
    # Notice that we don't have to put the create view above the detail view because, unlike Express, Django won't match a route unless the second segment has an integer (and therefore it won't match 'create' to the integer above)
    path('dresses/create/', views.DressCreate.as_view(), name='dresses_create'),
    # Note: we must use pk as named parameter instead of dress_id; this is convention for CBVs that work with model instances
    path('dresses/<int:pk>/update/', views.DressUpdate.as_view(), name='dresses_update'),
    path('dresses/<int:pk>/delete/', views.DressDelete.as_view(), name='dresses_delete'),
    path('dresses/<int:dress_id>/add_review/', views.add_review, name='add_review'),
    path('dresses/<int:dress_id>/add_photo/', views.add_photo, name='add_photo'),
    path('dresses/<int:dress_id>/assoc_store/<int:store_id>/', views.assoc_store, name='assoc_store'),
    path('dresses/<int:dress_id>/unassoc_store/<int:store_id>/', views.unassoc_store, name='unassoc_store'),
    path('stores/', views.StoreList.as_view(), name='stores_list'),
    path('stores/<int:pk>/', views.StoreDetail.as_view(), name='stores_detail'),
    path('stores/create/', views.StoreCreate.as_view(), name='stores_create'),
    path('stores/<int:pk>/delete/', views.StoreDelete.as_view(), name='stores_delete'),
    path('stores/<int:pk>/update/', views.StoreUpdate.as_view(), name='stores_update'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from localflavor.ca.models import CAProvinceField, CAPostalCodeField

RATING_CHOICES = [(i, i) for i in range(1, 6)]

# Create your models here.
class Store(models.Model):
    name = models.CharField(max_length=50) #CharField max_length defaults to 200
    street_address = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    province = CAProvinceField(default='ON')
    postal_code = CAPostalCodeField()
    website_url = models.URLField('Website URL') #URLField max_length defaults to 200

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse('stores_detail', kwargs={'pk': self.pk})
    
    class Meta:
        ordering = ['name']

class Dress(models.Model):
    STYLE_CHOICES = {
        'a_line': 'A-line',
        'ball_gown': 'Ball gown',
        'fit_and_flare': 'Fit-and-flare',
        'mermaid_trumpet': 'Mermaid or trumpet',
        'sheath': 'Sheath',
        'short': 'Short',
    }

    name = models.CharField(max_length=50)
    designer = models.CharField(max_length=50)
    collection = models.CharField(max_length=50, blank=True)
    style = models.CharField(
        max_length=15,
        choices=STYLE_CHOICES,
    )
    stores = models.ManyToManyField(Store)

    def __str__(self):
        return f"{self.designer}: {self.name}"
    
    # Django recommends get_absolute_url method in Model instead of success_url in view function because it will redirect the user after they either create OR update a dress (instead of defining a success_url in both view functions)
    def get_absolute_url(self):
        return reverse('detail', kwargs={'dress_id': self.id})
        # reverse function is similar to url tag; redirects user to appropriate path (detail) and populates necessary route parameters from kwargs (dress_id)
    
    class Meta:
        ordering = ['name']

class Review(models.Model):
    created_at = models.DateTimeField(default=timezone.now) # Swapping what's in parens for auto_now_add=True would work too (limitation: we wouldn't be able to modify this field, which should also be fine in this cased)
    reviewer_name = models.CharField('Name', max_length=50)
    rating = models.PositiveIntegerField(
        choices=RATING_CHOICES,
        default=RATING_CHOICES[-1][-1],
    )
    text = models.TextField('Comments and Feedback', max_length=300)
    dress = models.ForeignKey(Dress, on_delete=models.CASCADE)
    # Note that the column for FK in the reviews table will be called dress_id (Django default behaviour)
    # First argument: parent Model
    # on_delete=models.CASCADE is required or one-to-many relationships. If a Dress record is delete, all child Reviews will be deleted automatically as well - prevents 'orphan' records

    def __str__(self):
        return f"{self.reviewer_name} ({self.rating}): {self.text}"
    
    class Meta:
        ordering = ['-created_at']

class Photo(models.Model):
    url = models.CharField(max_length=300)
    dress = models.ForeignKey(Dress, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for dress_id: {self.dress_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Review

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['reviewer_name', 'rating', 'text']

main_app/views.py
import os
import uuid
import boto3
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

from .models import Dress, Store, Photo
from .forms import ReviewForm

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def dresses_index(request):
    # We are namespacing the index.html template by putting it in a new tempates/dresses folder for organization purposes
    # We pass a dictionary as a third positional argument in render; we can access the values in the template by using the key 'dresses'
    dresses = Dress.objects.all()
    return render(request, 'dresses/index.html', {
        'dresses': dresses
    })

def dresses_detail(request, dress_id):
    dress = Dress.objects.get(id=dress_id)
    # Create a list of the store ids a dress DOES have
    store_id_list = dress.stores.all().values_list('id')
    # Then, query for stores whose ids are not in the list using exclude
    # Exclude is similar to filter except that it returns objects that DON'T meet the criteria
    # id__in is a Django 'field lookup' that checks if the model's id is in a list
    stores_not_carrying = Store.objects.exclude(id__in=store_id_list)
    review_form = ReviewForm()
    return render(request, 'dresses/detail.html', {
        'dress': dress,
        'review_form': review_form,
        'stores_not_carrying': stores_not_carrying
    })

def add_review(request, dress_id):
    # Create a ModelForm instance using the data in request.POST (which is similar to req.body in Express)
    form = ReviewForm(request.POST)
    # Validate the form
    if form.is_valid():
        new_review = form.save(commit=False)
        new_review.dress_id = dress_id
        new_review.save()
    
    # Always redirect instead of render if data has been changed in the database
    return redirect('detail', dress_id=dress_id)

def add_photo(request, dress_id):
    # photo-file will be name attribute on <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # generate uniqu "key" for S3 with image file extension
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            # Build full url string:
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            # Create a photo object ans assign to dress_id (if we already got the dress object within this function, we could have created the object from that side of the relationship too)
            Photo.objects.create(url=url, dress_id=dress_id)
        except Exception as e:
            print('An error occurred uploading file to S3')
            print(e)
    return redirect('detail', dress_id=dress_id)

def assoc_store(request, dress_id, store_id):
    Dress.objects.get(id=dress_id).stores.add(store_id)
    # Note that in the above, we add the store_id instead of the store object
    return redirect('detail', dress_id=dress_id)

def unassoc_store(request, dress_id, store_id):
    Dress.objects.get(id=dress_id).stores.remove(store_id)
    return redirect('detail', dress_id=dress_id)

class DressCreate(CreateView):
    model = Dress
    fields = ['name', 'designer', 'collection', 'style'] # fields can be used to limit or change the ordering of attributes from the model that are generated in the ModelForm

class DressUpdate(UpdateView):
    model = Dress
    fields = '__all__'

class DressDelete(DeleteView):
    model = Dress
    success_url = '/dresses'

class StoreList(ListView):
    model = Store

class StoreDetail(DetailView):
    model = Store

class StoreCreate(CreateView):
    model = Store
    fields = '__all__'

class StoreUpdate(UpdateView):
    model = Store
    fields = ['street_address', 'city', 'province', 'postal_code', 'website_url']

class StoreDelete(DeleteView):
    model = Store
    success_url = '/stores'

main_app/templates/dresses/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Dress: {{ dress.name }}</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ dress.name }}</span>
                <p>Designer: {{ dress.designer }}</p>
                {% if dress.collection %}
                <p>Collection: {{ dress.collection }}</p>
                {% endif %}
                <p>Style: {{ dress.get_style_display }}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'dresses_update' dress.id %}">Edit</a>
                <a href="{% url 'dresses_delete' dress.id %}">Delete</a>
            </div>
        </div>

        <!-- Note the use of the for...empty template tags
            Also note that we do not invoke methods in DTL (Django templates automatically call an attribute if it's a function) -->
        {% for photo in dress.photo_set.all %}
        <img class="responsive-img card-panel" src="{{ photo.url }}" alt="Dress Photo">
        {% empty %}
        <div class="card-panel teal-text center-align">No photos uploaded yet...</div>
        {% endfor %}

        <form action="{% url 'add_photo' dress.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
            {% csrf_token %}
            <input type="file" name="photo-file">
            <br><br>
            <button type="submit" class="btn">Upload Photo</button>
        </form>
        
    </div>
    <div class="col s6">
        <form action="{% url 'add_review' dress.id %}" method="POST">
            {% csrf_token %}
            {{ review_form.as_p }}
            <button type="submit" class="btn">Submit</button>
        </form>
        <table class="striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Rating</th>
                    <th>Review</th>
                </tr>
            </thead>
            <tbody>
                <!-- Note that we do not add parens after .all -->
                {% for review in dress.review_set.all %}
                <tr>
                    <td>{{ review.reviewer_name }}</td>
                    <td>{{ review.rating }}</td>
                    <td>{{ review.text }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<hr>
<div class="row">
    <div class="col s6">
        <h4>Stores Carrying {{ dress.name }}:</h4>
        {% if dress.stores.count %}
        {% for store in dress.stores.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ store.name }}</span>
                <p>{{ store.street_address }}, {{ store.city }}, {{ store.province }}</p>
            </div>
            <div class="card-action">
                <form action="{% url 'unassoc_store' dress.id store.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn">Remove</button>
                </form>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <p>{{ dress.name }} is not currently available in stores near you 😔</p>
        {% endif %}
    </div>
    <div class="col s6">
        <h4>Other Stores:</h4>
        {% if stores_not_carrying.count %}
        {% for store in stores_not_carrying %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ store.name }}</span>
                <p>{{ store.street_address }}, {{ store.city }}, {{ store.province }}</p>
            </div>
            <div class="card-action">
                <form action="{% url 'assoc_store' dress.id store.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn">Add</button>
                </form>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <p>No more stores to add</p>
        {% endif %}
    </div>
</div>

<!-- We want the following JS to run after the elements are in the DOM, so we put the JS at the bottom of the template -->
<script>
    // To initialize the select for rating:
    const selectEl = document.getElementById('id_rating');
    M.FormSelect.init(selectEl);
</script>

{% endblock content %}

main_app/templates/dresses/index.html
{% extends 'base.html' %}
{% block content %}

<h1>All Dresses</h1>

{% for dress in dresses %}
<a href="{% url 'detail' dress.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ dress.name }}</span>
            <p>Designer: {{ dress.designer }}</p>
            <p>Collection: {{ dress.collection }}</p>
            <p>Style: {{ dress.get_style_display }}</p>
        </div>
    </div>
</a>
{% endfor %}

{% endblock content %}